Scripts

diff --git a/bin/dl-youtube b/bin/dl-youtube
--- a/bin/dl-youtube
+++ b/bin/dl-youtube
@@ -14,6 +14,21 @@ for url in "$@"; do
     IDS+=("${BASH_REMATCH[1]}")
   elif [[ "$url" =~ .*[?\&]v=([-_a-zA-Z0-9]{11})\&.*$ ]]; then
     IDS+=("${BASH_REMATCH[1]}")
+  elif [[ "$url" =~ .*/playlist.*[?\&]list=.*$ ]]; then
+    echo "Found playlist URL: $url"
+
+    tmp="$(mktemp)"
+    youtube-dl -j --flat-playlist "$url" >"$tmp"
+    if [[ $? -ne 0 ]]; then
+      rm -f "$tmp"
+      echo "ERROR: failed to fetch playlist $url"
+      exit 1
+    fi
+
+    for x in $(cat "$tmp" | egrep -o '"id": "[-_A-Za-z0-9]{11}"' | egrep -o '[^"]{11}'); do
+      echo "Found video: $x"
+      IDS+=("$x")
+    done
   else
     echo "Unrecognized URL: $url"
     exit 1
@@ -50,6 +65,7 @@ for id in "${IDS[@]}"; do
       continue;
     fi
     mv -f "$tmpdir"/*"$id"* ./
+    rmdir "$tmpdir"
     break
   done
 done
